//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C3.Reporting.CMT.Core.Caching {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class CacheSample : global::System.Configuration.ApplicationSettingsBase {
        
        private static CacheSample defaultInstance = ((CacheSample)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CacheSample())));
        
        public static CacheSample Default {
            get {
                return defaultInstance;
            }
        }
    }
}
