///////////////////////////////////////////////////////////////
// This is generated code. 
//////////////////////////////////////////////////////////////
// Code is generated using LLBLGen Pro version: 5.2
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
// Templates version: 
//////////////////////////////////////////////////////////////
using System;
using System.Data;
using Mecca.CMT.DAL;
using Mecca.CMT.DAL.HelperClasses;
using System.Collections.Generic;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Mecca.CMT.DAL.FactoryClasses
{
	/// <summary>Generates IEntityFields instances for different kind of Entities.</summary>
	public static partial  class EntityFieldsFactory
	{
		private static readonly Dictionary<Mecca.CMT.DAL.EntityType, string> _entityTypeNamesCache = new Dictionary<Mecca.CMT.DAL.EntityType, string>();

		/// <summary>static ctor which initializes the static entity type cache.</summary>
		static EntityFieldsFactory()
		{
			foreach(Mecca.CMT.DAL.EntityType value in Enum.GetValues(typeof(Mecca.CMT.DAL.EntityType)))
			{
				_entityTypeNamesCache.Add(value, Enum.GetName(typeof(Mecca.CMT.DAL.EntityType), value));
			}
		}	
	
		/// <summary>General factory entrance method which will return an EntityFields object with the format generated by the factory specified</summary>
		/// <param name="relatedEntityType">The type of entity the fields are for</param>
		/// <returns>The IEntityFields instance requested</returns>
		public static IEntityFields CreateEntityFieldsObject(Mecca.CMT.DAL.EntityType relatedEntityType)
		{
			return FieldInfoProviderSingleton.GetInstance().GetEntityFields(InheritanceInfoProviderSingleton.GetInstance(), PersistenceInfoProviderSingleton.GetInstance(), _entityTypeNamesCache[relatedEntityType]);
		}
		
		/// <summary>General method which will return an array of IEntityFieldCore objects, used by the InheritanceInfoProvider. Only the fields defined in the entity are returned, no inherited fields.</summary>
		/// <param name="entityName">the name of the entity to get the fields for. Example: "CustomerEntity"</param>
		/// <returns>array of IEntityFieldCore fields, defined in the entity with the name specified</returns>
		internal static IEntityFieldCore[] CreateFields(string entityName)
		{
			return FieldInfoProviderSingleton.GetInstance().GetEntityFieldsArray(entityName, PersistenceInfoProviderSingleton.GetInstance());
		}

		/// <summary>General factory entrance method which will return a TypedView EntityFields object with the format generated by the factory specified</summary>
		/// <param name="relatedTypedViewType">The type of typed view the fields are for</param>
		/// <returns>The IEntityFields instance requested</returns>
		public static IEntityFields CreateTypedViewEntityFieldsObject(TypedViewType relatedTypedViewType)
		{
			IEntityFields fieldsToReturn=null;
			switch(relatedTypedViewType)
			{
				case TypedViewType.Campaign1TypedView:
					fieldsToReturn = CreateCampaign1TypedViewEntityFields();
					break;
				case TypedViewType.CampaignOwner1TypedView:
					fieldsToReturn = CreateCampaignOwner1TypedViewEntityFields();
					break;
				case TypedViewType.CampaignType1TypedView:
					fieldsToReturn = CreateCampaignType1TypedViewEntityFields();
					break;
				case TypedViewType.Channel1TypedView:
					fieldsToReturn = CreateChannel1TypedViewEntityFields();
					break;
				case TypedViewType.ChannelCustomer1TypedView:
					fieldsToReturn = CreateChannelCustomer1TypedViewEntityFields();
					break;
				case TypedViewType.ChannelItem1TypedView:
					fieldsToReturn = CreateChannelItem1TypedViewEntityFields();
					break;
				case TypedViewType.ChannelOwner1TypedView:
					fieldsToReturn = CreateChannelOwner1TypedViewEntityFields();
					break;
				case TypedViewType.ChannelType1TypedView:
					fieldsToReturn = CreateChannelType1TypedViewEntityFields();
					break;
				case TypedViewType.RedemptionCode1TypedView:
					fieldsToReturn = CreateRedemptionCode1TypedViewEntityFields();
					break;
			}
			return fieldsToReturn;
		}

		/// <summary>Creates a complete EntityFields instance for the Campaign1Entity.</summary>
		/// <returns></returns>
		private static IEntityFields CreateCampaign1TypedViewEntityFields()
		{
			IEntityFields fieldsToReturn = new EntityFields((int)Campaign1FieldIndex.AmountOfFields, null, FieldInfoProviderSingleton.GetInstance().GetFieldIndexes("Campaign1TypedView"));
			for(int i=0;i<(int)Campaign1FieldIndex.AmountOfFields;i++)
			{
				fieldsToReturn[i] = EntityFieldFactory.Create((Campaign1FieldIndex)i);
			}
			return fieldsToReturn;
		}

		/// <summary>Creates a complete EntityFields instance for the CampaignOwner1Entity.</summary>
		/// <returns></returns>
		private static IEntityFields CreateCampaignOwner1TypedViewEntityFields()
		{
			IEntityFields fieldsToReturn = new EntityFields((int)CampaignOwner1FieldIndex.AmountOfFields, null, FieldInfoProviderSingleton.GetInstance().GetFieldIndexes("CampaignOwner1TypedView"));
			for(int i=0;i<(int)CampaignOwner1FieldIndex.AmountOfFields;i++)
			{
				fieldsToReturn[i] = EntityFieldFactory.Create((CampaignOwner1FieldIndex)i);
			}
			return fieldsToReturn;
		}

		/// <summary>Creates a complete EntityFields instance for the CampaignType1Entity.</summary>
		/// <returns></returns>
		private static IEntityFields CreateCampaignType1TypedViewEntityFields()
		{
			IEntityFields fieldsToReturn = new EntityFields((int)CampaignType1FieldIndex.AmountOfFields, null, FieldInfoProviderSingleton.GetInstance().GetFieldIndexes("CampaignType1TypedView"));
			for(int i=0;i<(int)CampaignType1FieldIndex.AmountOfFields;i++)
			{
				fieldsToReturn[i] = EntityFieldFactory.Create((CampaignType1FieldIndex)i);
			}
			return fieldsToReturn;
		}

		/// <summary>Creates a complete EntityFields instance for the Channel1Entity.</summary>
		/// <returns></returns>
		private static IEntityFields CreateChannel1TypedViewEntityFields()
		{
			IEntityFields fieldsToReturn = new EntityFields((int)Channel1FieldIndex.AmountOfFields, null, FieldInfoProviderSingleton.GetInstance().GetFieldIndexes("Channel1TypedView"));
			for(int i=0;i<(int)Channel1FieldIndex.AmountOfFields;i++)
			{
				fieldsToReturn[i] = EntityFieldFactory.Create((Channel1FieldIndex)i);
			}
			return fieldsToReturn;
		}

		/// <summary>Creates a complete EntityFields instance for the ChannelCustomer1Entity.</summary>
		/// <returns></returns>
		private static IEntityFields CreateChannelCustomer1TypedViewEntityFields()
		{
			IEntityFields fieldsToReturn = new EntityFields((int)ChannelCustomer1FieldIndex.AmountOfFields, null, FieldInfoProviderSingleton.GetInstance().GetFieldIndexes("ChannelCustomer1TypedView"));
			for(int i=0;i<(int)ChannelCustomer1FieldIndex.AmountOfFields;i++)
			{
				fieldsToReturn[i] = EntityFieldFactory.Create((ChannelCustomer1FieldIndex)i);
			}
			return fieldsToReturn;
		}

		/// <summary>Creates a complete EntityFields instance for the ChannelItem1Entity.</summary>
		/// <returns></returns>
		private static IEntityFields CreateChannelItem1TypedViewEntityFields()
		{
			IEntityFields fieldsToReturn = new EntityFields((int)ChannelItem1FieldIndex.AmountOfFields, null, FieldInfoProviderSingleton.GetInstance().GetFieldIndexes("ChannelItem1TypedView"));
			for(int i=0;i<(int)ChannelItem1FieldIndex.AmountOfFields;i++)
			{
				fieldsToReturn[i] = EntityFieldFactory.Create((ChannelItem1FieldIndex)i);
			}
			return fieldsToReturn;
		}

		/// <summary>Creates a complete EntityFields instance for the ChannelOwner1Entity.</summary>
		/// <returns></returns>
		private static IEntityFields CreateChannelOwner1TypedViewEntityFields()
		{
			IEntityFields fieldsToReturn = new EntityFields((int)ChannelOwner1FieldIndex.AmountOfFields, null, FieldInfoProviderSingleton.GetInstance().GetFieldIndexes("ChannelOwner1TypedView"));
			for(int i=0;i<(int)ChannelOwner1FieldIndex.AmountOfFields;i++)
			{
				fieldsToReturn[i] = EntityFieldFactory.Create((ChannelOwner1FieldIndex)i);
			}
			return fieldsToReturn;
		}

		/// <summary>Creates a complete EntityFields instance for the ChannelType1Entity.</summary>
		/// <returns></returns>
		private static IEntityFields CreateChannelType1TypedViewEntityFields()
		{
			IEntityFields fieldsToReturn = new EntityFields((int)ChannelType1FieldIndex.AmountOfFields, null, FieldInfoProviderSingleton.GetInstance().GetFieldIndexes("ChannelType1TypedView"));
			for(int i=0;i<(int)ChannelType1FieldIndex.AmountOfFields;i++)
			{
				fieldsToReturn[i] = EntityFieldFactory.Create((ChannelType1FieldIndex)i);
			}
			return fieldsToReturn;
		}

		/// <summary>Creates a complete EntityFields instance for the RedemptionCode1Entity.</summary>
		/// <returns></returns>
		private static IEntityFields CreateRedemptionCode1TypedViewEntityFields()
		{
			IEntityFields fieldsToReturn = new EntityFields((int)RedemptionCode1FieldIndex.AmountOfFields, null, FieldInfoProviderSingleton.GetInstance().GetFieldIndexes("RedemptionCode1TypedView"));
			for(int i=0;i<(int)RedemptionCode1FieldIndex.AmountOfFields;i++)
			{
				fieldsToReturn[i] = EntityFieldFactory.Create((RedemptionCode1FieldIndex)i);
			}
			return fieldsToReturn;
		}

		#region Included Code

		#endregion
	}
}
